SCORE_HP:
  PRED_PATH: "docker_data/input/preds"
  NATIVE_PATH: "docker_data/input/native/rp03.pdb"
  RESULT_PATH: "docker_data/output/rp03.csv"
  TIME_PATH: "docker_data/output/time_rp03.csv"
  LOG_PATH: "docker_data/logs/out.log"
  NORMALISATION: true
  VERBOSE: false
  PARAMS:
    mcq_threshold: 20
    mcq_mode: 2
  ALL_SCORES: ALL
  SORT_BY: RMSD