SCORE_HP:
  PRED_PATH: "docker_data/input/MODEL_1"
  NATIVE_PATH: "docker_data/input/NATIVE/1Z43.pdb"
  RESULT_PATH: "docker_data/output/test_tb_mcq.csv"
  TIME_PATH: "docker_data/output/time_tb_mcq.csv"
  LOG_PATH: "docker_data/logs/out.log"
  NORMALISATION: true
  VERBOSE: false
  PARAMS:
    mcq_threshold: 10
  ALL_SCORES:
    - ALL
#    - CGRNASP
#    - TB-MCQ
#    - MCQ
#    - RMSD
#    - P-VALUE
#    - INF
#    - DI
#    - MCQ
#    - TM-SCORE
#    - TM-SCORE (OST)
#    - lDDT
#    - CAD
#    - RASP
#    - CLASH
#    - BARNABA
  SORT_BY: RMSD
