SCORE_HP:
  PRED_PATH: "docker_data/input/MODEL_1"
  NATIVE_PATH: "docker_data/input/NATIVE/1Z43.pdb"
  RESULT_PATH: "docker_data/output/test_tb_mcq.csv"
  TIME_PATH: "docker_data/output/time_tb_mcq.csv"
  LOG_PATH: "docker_data/logs/out.log"
  NORMALISATION: true
  VERBOSE: false
  PARAMS:
    mcq_threshold: 20
    mcq_mode: 0
  ALL_SCORES:
    - RMSD
    - P-VALUE
    -INF
    - DI
    - MCQ
    - GDT-TS
    - CAD
    - RASP
    - BARNABA
    - DFIRE
    - rsRNASP
    - lDDT
    - TM-SCORE (OST)
    - TM-SCORE
    - QS-SCORE
    - LCS-TA
    - CGRNASP
    - TB-MCQ
  SORT_BY: RMSD