version: "3.8"
services:
  rnadvisor:
    build:
      context: .
      target: release
      dockerfile: Dockerfile
    image: rnadvisor
    volumes:
      - ./docker_data:/app/docker_data
      - ./config.yaml:/app/config.yaml
    command: --config_path=./config.yaml
    stdin_open: true
    tty: true
    restart: no

